### ISSUE TITLE
feature suggestion: send all output to sever 

### ISSUE THREAD

**Issue by royharoush** [opsdisk/dnmapR#1]
Hi, 
one of the main issues with dnmap is that it only sends the nmap file to the server. 
could you please add an option to send all outputs to the server (xml,gnmap,nmap). 
Thanks ! 
Roy

**Comment by opsdisk** [comment]
Hi Roy,

With the -f switch, you specify a file that has the exact nmap command to run.  You can specify the nmap switch "-oA" to output all formats.  For example:

Server
```
echo nmap 192.168.100.2 -oA results -p 22,80,443 -A -n -Pn > nmap.txt
python dnmapR_server.py -P server.pem -f nmap.txt
```

Client
```
python dnmapR_client.py
```

That resulted in results.gnmap, results.nmap, and results.xml in the nmap_output folder.  Hope that helps.

**Comment by royharoush** [comment]
Hi,
I know its possible to specify -oA, but dnmap does not retreive all of the files back to the server, only the nmap file. 
i have tried making the modifications myself, but to not avail :\
in Mininions there's a solution for that, but i wasnt able to to use that code in dnmapr (and minions have other problems for me im afraid).

**Comment by opsdisk** [comment]
Hi Roy,

I see what you mean now.  After taking a look at the code again and trying some stuff, an easy solution wasn't obvious given how this was written and designed by the original author.

A more elegant solution would be to leverage scp/rsync/samba through the SSH tunnels to either write the output directly to the server or sync up the server/client folders.  Setting up a temporary samba/ssh server (that only exists when the dnmapR_server.py is running) from within the server code means you wouldn't have to have those services started on the operating system.  That could be implemented in Python, but may take me a while.  For the time being, a simple scp after the scanning is done is all I can provide now:

```
scp user@vps1:/path/to/nmap_output/* .
scp user@vps2:/path/to/nmap_output/* .
```

**Comment by royharoush** [comment]
this is what i ended up doing, the only thing is scp required a password.
my scp solution includes ssh-agent and certificates, so i can automate access to my 90 scanning machines.
 
if you ever need it , here's the reference process.

```
eval $(ssh-agent)
ssh-add id_rsa 
for i in $(cat ip); do scp -oStrictHostKeyChecking=no   -o "ForwardAgent=yes"  -i id_rsa root@$i:/nmap_output/* ./ ;done
```
you would obviously need to setup your machines with certificate and all that. 

back to the point. 
Sixdub managed to implement it in Minions(supposedly), but i couldn't convert his code to your version, or even the original version.

you can see his client here

https://github.com/sixdub/Minions/blob/master/client/dnmap_client.py
in the function dataReceived(self, line): , he has a handling of all output types. 

```
if nmap_returncode >= 0:
					# Nmap ended ok and the files were created
					if os.path.isfile(nmap_output_file+".xml") and os.path.isfile(nmap_output_file+".gnmap") and os.path.isfile(nmap_output_file+".nmap"):
						with open(nmap_output_file+".xml","r") as f:
							XMLData=f.read()
						with open(nmap_output_file+".gnmap","r") as f:
							GNmapData=f.read()
						with open(nmap_output_file+".nmap","r") as f:
							NmapData=f.read()

						xml_linesep="\r\n#XMLOUTPUT#\r\n"
						gnmap_linesep="\r\n#GNMAPOUTPUT#\r\n"
						# Tell the server that we are sending the nmap output
						print '\tSending output to the server...'
						line = 'Nmap Output File:{0}:'.format(nmap_output_file.strip('\n').strip('\r'))
						if debug:
							print ' -- Line sent: {0}'.format(line)
						self.sendLine(line)
						line =raw_nmap_output+xml_linesep+XMLData+gnmap_linesep+GNmapData
						self.sendLine(line)
						if debug:
							print ' -- Line sent: {0}'.format(line)
						line = 'Nmap Output Finished:{0}:'.format(nmap_output_file.strip('\n').strip('\r'))
						if debug:
							print ' -- Line sent: {0}'.format(line)
						self.sendLine(line)

						# Move nmap output files to its directory
						os.system('mv *.nmap nmap_output > /dev/null 2>&1')
						os.system('mv *.gnmap nmap_output > /dev/null 2>&1')
						os.system('mv *.xml nmap_output > /dev/null 2>&1')

						# Ask for another command.
						# 'Client ID' text must be sent to receive another command
						print 'Waiting for more commands....'
						#line = 'Send more commands to Client ID:{0}:Alias:{1}:'.format(str(client_id),str(alias))
						line = 'Send more commands'
						if debug:
							print ' -- Line sent: {0}'.format(line)
						self.sendLine(line)
```

but again, i didn't manage to migrate that code successfully.

**Comment by archey** [comment]
I was able to migrate the code over to dnmapR so that will transfer all nmap files that are built wth -oA over to the server. It can easily be removed from the client server as well.

**Comment by royharoush** [comment]
Could you pull request your branch ?

**Comment by archey** [comment]
Yeah I was going to let me clean it up and Ill PR it

**Comment by archey** [comment]
Pull request submitted

**Comment by opsdisk** [comment]
I'm no longer maintaining this project, but actively working on https://github.com/rackerlabs/scantron
