### ISSUE TITLE
dnmapr does not generate a dnmaptrace file

### ISSUE THREAD

**Issue by royharoush** [opsdisk/dnmapR#2]
this file is critical for resuming dnmap server, so it will not rerun previously executed tasks 

![image](https://cloud.githubusercontent.com/assets/8113056/22408002/0a4f3ed8-e67a-11e6-89d3-dfbede75cbdd.png)

you can see that if you restart the client or the server they will start the tasks all over again

**Comment by opsdisk** [comment]
Hi royharoush - Are you familiar with the "--resume" option (https://nmap.org/book/man-output.html)?  I honestly didn't know it existed until you brought it up...looks like it's only for -oN output files.  You'd have to modify your "commands.txt" file to add the nmap switch or I could add a '-r' switch to the client to add the '--resume' to nmap to try and resume a past scan.  Thoughts?

**Comment by royharoush** [comment]
Im refering to the dnmaptrace file on the server side, it keeps the last
command that was completed by a client. It's in the original dnmap code.
The dnmap server server first loads a command file, then looks for the same
file with a .dnmaptrace extension so it will not reissue the same command
again.

**Comment by opsdisk** [comment]
Should be good to go now...just git pull on master.  Let me know if it works and I'll close the issue.

**Comment by royharoush** [comment]
seems fixed.
Thanks.
